<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Bulk Shipping Summary</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
        }
        h2 {
            background-color: #f4f4f4;
            padding: 10px;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            margin-bottom: 20px;
        }
        table th, table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        table th {
            background-color: #f0f0f0;
        }
        .success {
            color: green;
        }
        .failed {
            color: red;
        }
        a.label-link {
            color: #1a73e8;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <h1>Bulk Shipping Summary</h1>

    <p>Status: <strong>{{ ucfirst($history->status) }}</strong></p>
    <p>Total Orders Processed: {{ $summary['total_processed'] }}</p>
    <p>Successful Orders: <span class="success">{{ $summary['success_count'] }}</span></p>
    <p>Failed Orders: <span class="failed">{{ $summary['failed_count'] }}</span></p>

    @if($successOrders->count() > 0)
        <h2>Successful Orders</h2>
        <table>
            <thead>
                <tr>
                    <th>Sr. No.</th>
                    <th>Order Number</th>
                    <th>Tracking Number</th>
                    <th>Tracking URL</th>
                    <th>Label URL</th>
                    <th>Marketplace</th>
                </tr>
            </thead>
            <tbody>
                @foreach($successOrders as $order)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $order->order_number }}</td>
                        <td>{{ $order->tracking_number ?? 'N/A' }}</td>
                        <td>
                            @if($order->tracking_url)
                                <a href="{{ $order->tracking_url }}" target="_blank">Track</a>
                            @else
                                N/A
                            @endif
                        </td>
                        <td>
                            @if($order->label_url)
                                <a href="{{ $order->label_url }}" target="_blank" class="label-link">Download Label</a>
                            @else
                                N/A
                            @endif
                        </td>
                        <td>{{ $order->marketplace ?? '-' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    @if($failedOrders->count() > 0)
        <h2>Failed Orders</h2>
        <table>
            <thead>
                <tr>
                    <th>Order Number</th>
                    <th>Tracking Number</th>
                    <th>Tracking URL</th>
                    <th>Label URL</th>
                    <th>Marketplace</th>
                </tr>
            </thead>
            <tbody>
                @foreach($failedOrders as $order)
                    <tr>
                        <td>{{ $order->order_number }}</td>
                        <td>{{ $order->tracking_number ?? 'N/A' }}</td>
                        <td>
                            @if($order->tracking_url)
                                <a href="{{ $order->tracking_url }}" target="_blank">Track</a>
                            @else
                                N/A
                            @endif
                        </td>
                        <td>
                            @if($order->label_url)
                                <a href="{{ $order->label_url }}" target="_blank" class="label-link">Download Label</a>
                            @else
                                N/A
                            @endif
                        </td>
                        <td>{{ $order->marketplace ?? '-' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <p>Generated by ShipHub System</p>
</body>
</html>
